-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 25, 2021 at 07:16 PM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 8.0.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `songs`
--

-- --------------------------------------------------------

--
-- Table structure for table `song_1600`
--

CREATE TABLE `song_1600` (
  `song_number_1600` int(4) NOT NULL,
  `title` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `display` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `link` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `content` varchar(4096) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `song_1600`
--

INSERT INTO `song_1600` (`song_number_1600`, `title`, `display`, `link`, `content`) VALUES
(1, 'Laßt uns das Kindlein wiegen', 'Laßt uns das Kindlein wiegen (1604)', 'lasstunsdaskindleinwiegen', '<p>\r\nLaßt uns das Kindlein wiegen,<br>\r\ndas Herz zum Kripplein biegen.<br>\r\nLaßt uns im Geist erfreuen,<br>\r\ndas Kindlein benedeien:<br>\r\n„O Jesulein süß, o Jesulein süß.“<br>\r\n</p>\r\n<p>\r\nLaßt uns dem Kindlein neigen,<br>\r\nihm Lieb und Dienst erzeigen<br>\r\nLaßt uns doch jubilieren<br>\r\nund freudig triumphieren<br>\r\n„O Jesulein süß, o Jesulein süß.“<br>\r\n</p>\r\n<p>\r\nLaßt uns dem Kindlein singen,<br>\r\nihm unser Opfer bringen,<br>\r\nihm alle Ehr erweisen<br>\r\nmit Loben und mit Preisen:<br>\r\n„O Jesulein süß, o Jesulein süß.“<br>\r\n</p>\r\n<p>\r\nLaßt uns sein Händlein und Füße<br>\r\nSein feurigs Herzlein grüßen<br>\r\nUnd ihn demütig ehren<br>\r\nAls unsern Gott und Herren!<br>\r\nO Jesulein süß!<br>\r\n</p>\r\n<p>\r\nLaßt unser Stimmlein schallen<br>\r\nEs wird dem Kindlein gefallen:<br>\r\nLaßt ihm ein Freudlein machen<br>\r\nDas Kindlein wird eins lachen.<br>\r\nO Jesulein süß!<br>\r\n</p>\r\n'),
(2, 'Als Maria die Jungfrau schon', 'Als Maria die Jungfrau schon (1608)', 'alsmariadiejungfrauschon', '<p>\r\nAls Maria, die Jungfrau schon<br>\r\nnun sollt gebären Gottes Sohn<br>\r\nkam sie zu Bethlehem in die Stadt<br>\r\ndie darzu Gott erwählet hat<br>\r\nGelobet muß sein das Kindelein<br>\r\ngeehrt muß sein das keusche Mägdelein<br>\r\nnun und ewiglich zu aller Zeit<br>\r\n</p>\r\n<p>\r\nSie kamen an eines Wirtes Tür<br>\r\nDa war kein Platz, sie blieb darfür<br>\r\nUnd ging heraus in eine Scheur<br>\r\nDie Herberg war der Jungfrau teur<br>\r\nGelobet muß sein das Kindelein<br>\r\ngeehrt muß sein das keusche Mägdelein<br>\r\nnun und ewiglich zu aller Zeit<br>\r\n</p>\r\n<p>\r\nO Bethlehem, o wann du wüß’t<br>\r\nWie diese Jungfrau schwanger ist<br>\r\nVom Heilgen Geist und gnadenvoll<br>\r\nEin jeder Mensch ihr dienen soll<br>\r\nGelobet muß sein das Kindelein<br>\r\ngeehrt muß sein das keusche Mägdelein<br>\r\nnun und ewiglich zu aller Zeit<br>\r\n</p>\r\n<p>\r\nJesum gebar sie in dem Stall<br>\r\nSie hatt keinen Platz im schönen Saal<br>\r\nSie band das Kind in Tüchlein rein<br>\r\nUnd legt es in das Krippelein<br>\r\nGelobet muß sein das Kindelein<br>\r\ngeehrt muß sein das keusche Mägdelein<br>\r\nnun und ewiglich zu aller Zeit<br>\r\n</p>\r\n<p>\r\nKommt her, seht zu, ihr reiche Leut<br>\r\nWie Jesus wird geboren heut<br>\r\nIn bloßem Stall, in kalter Nacht:<br>\r\nSollt ihr schlafen, wenn Jesus wacht?<br>\r\nGelobet muß sein das Kindelein<br>\r\ngeehrt muß sein das keusche Mägdelein<br>\r\nnun und ewiglich zu aller Zeit<br>\r\n</p>\r\n<p>\r\nViel warmer Kleider brauchet ihr<br>\r\nDarzu Kamin und Helles Feuer<br>\r\nIn Schnee und Frost eur König leit<br>\r\nSein Herz bezwingt die kalte Zeit<br>\r\nGelobet muß sein das Kindelein<br>\r\ngeehrt muß sein das keusche Mägdelein<br>\r\nnun und ewiglich zu aller Zeit<br>\r\n</p>\r\n<p>\r\nRüst zu eur Herz und Seelen rein<br>\r\nDem allerliebsten Jesulein<br>\r\nDer Liebe Feur ihm zündet an<br>\r\nUnd laßt ihn nimmer von euch gahn<br>\r\nGelobet muß sein das Kindelein<br>\r\ngeehrt muß sein das keusche Mägdelein<br>\r\nnun und ewiglich zu aller Zeit<br>\r\n</p>\r\n'),
(3, 'Ach bleib mit deiner Gnade', 'Ach bleib mit deiner Gnade, Josua Stegmann (~1616)', 'achbleibmitdeinergnade', '<p>\r\nAch bleib mit deiner Gnade<br>\r\nbei uns, Herr Jesu Christ<br>\r\ndaß uns hinfort nicht schade<br>\r\ndes bösen Feindes List<br>\r\n</p>\r\n<p>\r\nAch bleib mit deinem Worte<br>\r\nbei uns, Erlöser wert<br>\r\ndaß uns beid´ hier und dorte<br>\r\nsei Güt´ und Heil beschert<br>\r\n</p>\r\n<p>\r\nAch bleib mit deinem Glanze<br>\r\nbei uns, du wertes Licht<br>\r\ndein´ Wahrheit uns umschanze<br>\r\ndamit wir irren nicht<br>\r\n</p>\r\n<p>\r\nAch bleib mit deinem Segen<br>\r\nbei uns, du reicher Herr<br>\r\ndein´ Gnad´ und all´s Vermögen<br>\r\nin uns reichlich vermehr<br>\r\n</p>\r\n<p>\r\nAch bleib mit deinem Schutze<br>\r\nbei uns, du starker Held<br>\r\ndaß uns der Feind nicht trutze<br>\r\nnoch fäll´ die böse Welt<br>\r\n</p>\r\n<p>\r\nAch bleib mit deiner Treue<br>\r\nbei uns, mein Herr und Gott<br>\r\nBeständigkeit verleihe<br>\r\nHilf uns aus aller Not!<br>\r\n</p>\r\n'),
(4, 'O Heiland reiß die Himmel auf', 'O Heiland reiß die Himmel auf, Friedrich von Langenfeld (1623)', 'oheilandreissdiehimmelauf', '<p>\r\nO Heiland, reiß die Himmel auf<br>\r\nHerab, herab, vom Himmel lauf!<br>\r\nReiß ab vom Himmel Tor und Tür<br>\r\nReiß ab, wo Schloß und Riegel für!<br>\r\n</p>\r\n<p>\r\nO Gott, ein Tau vom Himmel gieß<br>\r\nIm Tau herab, o Heiland, fließ.<br>\r\nIhr Wolken, brecht und regnet aus<br>\r\nDen König über Jakobs Haus.<br>\r\n</p>\r\n<p>\r\nO Erd´ schlag aus, schlag aus, o Erd´<br>\r\nDaß Berg und Tal grün alles werd´<br>\r\nO Erd´, herfür dies Blümlein bring<br>\r\nO Heiland, aus der Erden spring.<br>\r\n</p>\r\n<p>\r\nWo bleibst du, Trost der ganzen Welt<br>\r\nDarauf sie all´ ihr‘ Hoffnung stellt ?<br>\r\nO komm, ach komm vom höchsten Saal<br>\r\nKomm tröst uns hier im Jammertal<br>\r\n</p>\r\n<p>\r\nO klare Sonn’´ du schöner Stern<br>\r\nDich wollten wir anschauen gern.<br>\r\nO Sonn‘, geh auf, ohn´ deinen Schein<br>\r\nIn Finsternis wir alle sein.<br>\r\n</p>\r\n<p>\r\nHier leiden wir die größte Not<br>\r\nVor Augen steht der ewig´ Tod<br>\r\nAch komm, führ uns mit starker Hand<br>\r\nVom Elend zu dem Vaterland.<br>\r\n</p>\r\n<p>\r\nDa wollen wir all´ danken dir<br>\r\nUnserm Erlöser, für und für<br>\r\nDa wollen wir all´ loben dich<br>\r\nJe allzeit immer und ewiglich<br>\r\n</p>\r\n'),
(5, 'Macht hoch die Tür die Tor macht weit', 'Macht hoch die Tür die Tor macht weit, Georg Weissel (1635)', 'machthochdietuerdietormachtweit', '<p>\r\nMacht hoch die Tür die Tor macht weit<br>\r\nEs kommt der Herr der Herrlichkeit<br>\r\nEin König aller Königreich´<br>\r\nEin Heiland aller Welt zugleich<br>\r\nDer Heil und Leben mit sich bringt<br>\r\nDerhalben jauchzt, mit Freuden singt:<br>\r\nGelobet sei mein Gott<br>\r\nMein Schöpfer, reich von Rat!<br>\r\n</p>\r\n<p>\r\nEr ist gerecht, ein Helfer wert<br>\r\nSanftmütigkeit ist sein Gefährt<br>\r\nSein Königskron´ ist Heiligkeit<br>\r\nSein Zepter ist Barmherzigkeit<br>\r\nAll unsre Not zum End´ er bringt<br>\r\nDerhalben jauchzt, mit Freuden singt<br>\r\nGelobet sei mein Gott<br>\r\nMein Heiland, groß von Tat<br>\r\n</p>\r\n<p>\r\nO wohl dem Land, o wohl der Stadt<br>\r\nSo diesen König bei sich hat<br>\r\nWohl allen Herzen insgemein<br>\r\nDa dieser König ziehet ein<br>\r\nEr ist die rechte Freudensonn´<br>\r\nBringt mit sich lauter Freud´ und Wonn´<br>\r\nGelobet sei mein Gott<br>\r\nMein Tröster, früh und spat<br>\r\n</p>\r\n<p>\r\nMacht hoch die Tür die Tor´ macht weit<br>\r\nEur Herz zum Tempel zubereit´t<br>\r\nDie Zweiglein der Gottseligkeit<br>\r\nSteckt auf mit Andacht, Lust und Freud<br>\r\nSo kommt der König auch zu euch<br>\r\nJa Heil und Leben mit zugleich<br>\r\nGelobet sei mein Gott<br>\r\nVoll Rat, voll Tat, voll Gnad<br>\r\n</p>\r\n<p>\r\nKomm, o mein Heiland Jesu Christ<br>\r\nMein´s Herzens Tür dir offen ist<br>\r\nAch zeuch mit deiner Gnade ein<br>\r\nDein Freundlichkeit auch uns erschein<br>\r\nDein Heilger Geist uns führ und leit<br>\r\nDen Weg zur ewgen Seligkeit<br>\r\nDem Namen dein, o Herr<br>\r\nsei ewig Preis und Ehr<br>\r\n</p>\r\n'),
(6, 'Nun ruhen alle Wälder', 'Nun ruhen alle Wälder, Paul Gerhardt (1648)', 'nunruhenallewaelder', '<p>\r\nNun ruhen alle Wälder<br>\r\nVieh, Menschen, Städt und Felder<br>\r\nEs schläft die ganze Welt;<br>\r\nIhr aber, meine Sinnen<br>\r\nAuf auf, ihr sollt beginnen<br>\r\nWas eurem Schöpfer wohlgefällt<br>\r\n</p>\r\n<p>\r\nWo bist du, Sonne, blieben?<br>\r\nDie Nacht hat dich vertrieben,<br>\r\nDie Nacht, des Tages Feind;<br>\r\nFahr hin! Ein ander Sonne,<br>\r\nMein Jesus, meine Wonne,<br>\r\nGar hell in meinem Herzen scheint.<br>\r\n</p>\r\n<p>\r\nDer Tag ist nun vergangen,<br>\r\nDie güldnen Sterne prangen<br>\r\nAm blauen Himmelssaal;<br>\r\nAlso werd ich auch stehen,<br>\r\nWann mich wird heißen gehen<br>\r\nMein Gott aus diesem Jammertal.<br>\r\n</p>\r\n<p>\r\nDer Leib eilt nun zur Ruhe,<br>\r\nLegt ab das Kleid und Schuhe,<br>\r\nDas Bild der Sterblichkeit;<br>\r\nDie Zieh ich aus. Dagegen<br>\r\nWird Christus mir anlegen<br>\r\nDen Rock der Ehr und Herrlichkeit.<br>\r\n</p>\r\n<p>\r\nDas Haupt, die Füß und Hände<br>\r\nSind froh, daß nun zu Ende<br>\r\nDie Arbeit kommen sei;<br>\r\nHerz, freu dich, du sollst werden<br>\r\nVom Elend dieser Erden<br>\r\nUnd von der Sünden Arbeit frei.<br>\r\n</p>\r\n<p>\r\nNun geht, ihr matten Glieder,<br>\r\nGeht hin und legt euch nieder,<br>\r\nDer Betten ihr begehrt;<br>\r\nEs kommen Stund und Zeiten,<br>\r\nDa man euch wird bereiten<br>\r\nZur Ruh ein Bettlein in der Erd.<br>\r\n</p>\r\n<p>\r\nMein Augen stehn verdrossen,<br>\r\nIm Hui sind sie geschlossen,<br>\r\nWo bleibt denn Leib und Seel?<br>\r\nNimm sie zu deinen Gnaden,<br>\r\nSei gut für allem Schaden,<br>\r\nDu Aug und Wächter Israel.<br>\r\n</p>\r\n<p>\r\nBreit aus die Flügel beide,<br>\r\nO Jesu, meine freude,<br>\r\nUnd nimm dein Küchlein ein!<br>\r\nWill Satan mich verschlingen,<br>\r\nSo lass die Englein singen:<br>\r\nDies Kind soll unverletzet sein.<br>\r\n</p>\r\n<p>\r\nAuch euch, ihr meine Lieben,<br>\r\nSoll heute nicht betrüben!<br>\r\nKein Unfall noch Gefahr.<br>\r\nGott laß euch selig schlafen,<br>\r\nStell euch die güldnen Waffen<br>\r\nUms Bett und seiner Engel Schar.<br>\r\n</p>\r\n'),
(7, 'Es waren zwei Königskinder', 'Es waren zwei Königskinder (1700)', 'eswarenzweikoenigskinder', '<p>\r\nEs waren zwei Königskinder,<br>\r\nDie hatten einander so lieb,<br>\r\nSie konnten zusammen nicht kommen,<br>\r\nDas Wasser war viel zu tief.<br>\r\n</p>\r\n<p>\r\n„Ach, Liebster, könntest du schwimmen?<br>\r\nso schwimm doch herüber zu mir!<br>\r\nZwei Kerzen will ich anzünden,<br>\r\nUnd die sollen leuchten dir.“<br>\r\n</p>\r\n<p>\r\nDa war eine falsche Nonne,<br>\r\nDie tat, als ob sie schlief.<br>\r\nSie tat die Kerzen auslöschen<br>\r\nDer Jüngling der sank so tief<br>\r\n</p>\r\n<p>\r\nUnd als der Jüngling zu Grunde ging<br>\r\nso schrie sie und weinte sehr<br>\r\nsie ging mit verweinten Augen<br>\r\nwohl vor der Mutter Tür<br>\r\n</p>\r\n<p>\r\n„Ach Mutter, herzliebste Mutter,<br>\r\nDer Kopf tut mir so weh;<br>\r\nIch möcht so gern spazieren<br>\r\nan den tiefen, tiefen See.“<br>\r\n</p>\r\n<p>\r\n„Ach Tochter, liebe Tochter<br>\r\nallein darfst du nicht gehn<br>\r\nnimm deinen jüngsten Bruder<br>\r\nund der soll mit dir gehn“<br>\r\n</p>\r\n<p>\r\n„Ach Mutter, liebe Mutter,<br>\r\nmein Bruder ist ja noch ein Kind<br>\r\nder schießt ja alle Vögel<br>\r\ndie auf der Heide sind“<br>\r\n</p>\r\n<p>\r\n„Ach Tochter, liebe Tochter<br>\r\nallein darfst du nicht gehn<br>\r\nnimm deine jüngste Schwester<br>\r\nund die soll mit dir gehn“<br>\r\n</p>\r\n<p>\r\n„Ach Mutter, liebe Mutter,<br>\r\nmeine Schwester ist ja noch ein Kind<br>\r\nsie pflückt ja alle Blumen<br>\r\ndie auf der Heide sind“<br>\r\n</p>\r\n<p>\r\nDie Mutter ging nach der Kirche,<br>\r\nDie Tochter ging ihren Gang.<br>\r\nSie ging so lang spazieren,<br>\r\nBis sie den Fischer fand.<br>\r\n</p>\r\n<p>\r\n„Ach Fischer, liebster Fischer,<br>\r\nWillst du verdienen großen Lohn?<br>\r\nSo wirf dein Netz ins Wasser,<br>\r\nUnd fisch mir den Königssohn!“<br>\r\n</p>\r\n<p>\r\nEr senkte sein Netz ins Wasser,<br>\r\nund nahm sie in den Kahn<br>\r\nEr fischte und fischte so lange,<br>\r\nBis sie den Königssohn sahn.<br>\r\n</p>\r\n<p>\r\nWas nahm sie von ihrem Haupte<br>\r\neine goldene Königskron<br>\r\nSieh da, du edler Fischer<br>\r\ndas ist dein verdienter Lohn<br>\r\n</p>\r\n<p>\r\nWas nahm sie von ihrem Finger<br>\r\nein Ringlein von Gold so rot<br>\r\nSieh da du armer Fischer<br>\r\nkauf deinen Kindern Brot<br>\r\n</p>\r\n<p>\r\nSie schloß ihn in ihre Arme<br>\r\nUnd küßt‘ seinen bleichen Mund:<br>\r\nAch, Mündlein, könntest du sprechen,<br>\r\nSo würde mein Herz gesund.“<br>\r\n</p>\r\n<p>\r\nSie schwang um sich ihren Mantel<br>\r\nUnd sprang mit ihm ins Meer:<br>\r\n„Gut‘ Nacht, mein Vater und Mutter,<br>\r\nIhr seht mich nimmermehr‘!“<br>\r\n</p>\r\n<p>\r\nDa hörte man Glockengeläute,<br>\r\nDa hörte man Jammer und Not,<br>\r\nDa lagen zwei Königskinder,<br>\r\nDie sind alle beide tot.<br>\r\n</p>\r\n'),
(8, 'Hört der Engel helle Lieder', 'Hört der Engel helle Lieder (~1750)', 'hoertderengelhellelieder', '<p>\r\nHört der Engel helle Lieder,<br>\r\nklingen weit das Feld entlang,<br>\r\nund die Berge hallen wider<br>\r\nvon des Himmels Lobgesang.<br>\r\nGloria, Gloria, Gloria, Gloria in excelsis Deo.<br>\r\nGloria, Gloria, Gloria, Gloria in excelsis Deo.   <br>                     \r\n</p>\r\n<p>\r\nHirten, warum wird gesungen?<br>\r\nSagt uns eures Jubels Grund!<br>\r\nWas hat hier so hell geklungen?<br>\r\nWas tat euch der Engel kund?<br>\r\nGloria, Gloria, Gloria, Gloria in excelsis Deo.<br>\r\nGloria, Gloria, Gloria, Gloria in excelsis Deo. <br>                       \r\n</p>\r\n<p>\r\nGott hat Freude uns beschieden<br>\r\ndurch ein neugebornes Kind.<br>\r\nEs bringt allen Menschen Frieden,<br>\r\nwelche guten Willens sind.<br>\r\nGloria, Gloria, Gloria, Gloria in excelsis Deo.<br>\r\nGloria, Gloria, Gloria, Gloria in excelsis Deo. <br>                      \r\n</p>\r\n'),
(9, 'Das Leben ist ein Traum', 'Das Leben ist ein Traum, Johann Gleim (1784)', 'daslebenisteintraum', 'daslebenisteintraum'),
(10, 'Morgen, Kinder, wird\'s was geben', 'Morgen, Kinder, wird\'s was geben (~1780)', 'morgenkinderwirdswasgeben', '<p>\r\nMorgen, Kinder, wird’s was geben!<br>\r\nMorgen werden wir uns freu’n!<br>\r\nWelche Wonne, welches Leben<br>\r\nwird in unserm Hause sein!<br>\r\nEinmal werden wir noch wach,<br>\r\nheißa, dann ist Weihnachtstag!<br>\r\n</p>\r\n<p>\r\nWie wird dann die Stube glänzen<br>\r\nvon der großen Lichterzahl!<br>\r\nSchöner, als bei frohen Tänzen<br>\r\nein geputzter Kronensaal.<br>\r\nWißt ihr noch, wie vor’ges Jahr<br>\r\nes am heil’gen Abend war?<br>                \r\n</p>\r\n<p>\r\nWelch\' ein schöner Tag ist morgen!<br>\r\nViele Freunde hoffen wir;<br>\r\nuns\'re lieben Eltern sorgen<br>\r\nlange, lange schon dafür.<br>\r\nO gewiß, wer sie nicht ehrt,<br>\r\nist der ganzen Lust nicht wert!<br>                   \r\n</p>\r\n<p>\r\nMorgen, Kinder, wird\'s was geben,<br>\r\nmorgen werden wir uns freun!<br>\r\nWelch ein Jubel, welch ein Leben<br>\r\nwird in unserm Hause sein!<br>\r\nEinmal werden wir noch wach,<br>\r\nheißa dann ist Weihnachtstag!<br>                        \r\n</p>\r\n<p>\r\nWißt ihr noch die Spiele, Bücher<br>\r\nund das schöne Schaukelpferd,<br>\r\nschöne Kleider, woll’ne Tücher,<br>\r\nPuppenstube, Puppenherd?<br>\r\nMorgen strahlt der Kerzen Schein,<br>\r\nmorgen werden wir uns freu’n.   <br>                     \r\n</p>\r\n<p>\r\nWißt ihr noch mein Räderpferdchen?<br>\r\nMalchens nette Schäferin?<br>\r\nJettchens Küche mit dem Herdchen,<br>\r\nund dem blankgeputzten Zinn?<br>\r\nHeinrichs bunten Harlekin<br>\r\nmit der gelben Violin?  <br>                      \r\n</p>\r\n<p>\r\nWißt ihr noch den großen Wagen,<br>\r\nund die schöne Jagd von Blei?<br>\r\nUnsre Kleiderchen zum Tragen,<br>\r\nund die viele Nascherei?<br>\r\nMeinen fleiß’gen Sägemann<br>\r\nmit der Kugel unten dran? <br>                       \r\n</p>\r\n<p>\r\nWelch ein schöner Tag ist morgen!<br>\r\nNeue Freude hoffen wir.<br>\r\nUnsre guten Eltern sorgen<br>\r\nlange, lange schon dafür.<br>\r\nO gewiß, wer sie nicht ehrt,<br>\r\nist der ganzen Lust nicht wert.  <br>                     \r\n</p>\r\n<p>\r\nNein, ihr Schwestern und ihr Brüder,<br>\r\nlaßt uns ihnen dankbar sein,<br>\r\nund den guten Eltern wieder<br>\r\nZärtlichkeit und Liebe weih’n,<br>\r\nund aufs redlichste bemüh’n,<br>\r\nalles, was sie kränkt, zu flieh’n. <br>                      \r\n</p>\r\n<p>\r\nLaßt uns nicht bei den Geschenken<br>\r\nneidisch auf einander sehn;<br>\r\nsondern bei den Sachen denken:<br>\r\n„Wie erhalten wir sie schön,<br>\r\ndass uns ihre Niedlichkeit<br>\r\nlange noch nachher erfreut?“  <br>                      \r\n</p>\r\n'),
(11, 'Ein Schifflein sah ich fahren', 'Ein Schifflein sah ich fahren (1781)', 'einschiffleinsahichfahren', '<p>\r\nEin Schifflein sah ich fahren,<br>\r\nKapitän und Leutenant!<br>\r\nDarinnen waren geladen<br>\r\nDrei brave Kompanien Soldaten.<br>\r\nKapitän, Leutenant, Fähnerich, Sergeant,<br>\r\nNimm das Mädel,<br>\r\nNimm das Mädel bei der Hand!<br>\r\nSoldaten, Kameraden!<br>\r\nNehmt das Mädel,<br>\r\nNehmt das Mädel bei der Hand!<br>\r\n</p>\r\n<p>\r\nWas sollen die Soldaten essen,<br>\r\nKapitän und Leutenant?<br>\r\nGebrat’ne Fisch mit Kressen,<br>\r\nDas sollen die Soldaten essen!<br>\r\nKapitän, Leutenant….<br>\r\n</p>\r\n<p>\r\nWas sollen die Soldaten trinken,<br>\r\nKapitän und Leutenant?<br>\r\nDen besten Wein, der zu finden,<br>\r\nDen sollen die Soldaten trinken!<br>\r\nKapitän, Leutenant….                <br>        \r\n</p>\r\n<p>\r\nWo sollen die Soldaten schlafen,<br>\r\nKapitän und Leutenant?<br>\r\nBei ihrem Gewehr und Waffen,<br>\r\nDa müssen die Soldaten schlafen!<br>\r\nKapitän, Leutenant …..<br>\r\n</p>\r\n<p>\r\nWo sollen die Soldaten tanzen,<br>\r\nKapitän und Leutenant?<br>\r\nVor Harburg auf der Schanzen,<br>\r\nDa müssen die Soldaten tanzen!<br>\r\nKapitän, Leutenant ….<br>\r\n</p>\r\n<p>\r\nWie kommen die Soldaten in´n Himmel,<br>\r\nKapitän und Leutenant?<br>\r\nAuf einem weißen Schimmel,<br>\r\nDa reiten die Soldaten in’n Himmel.<br>\r\nKapitän, Leutenant…..<br>\r\n</p>\r\n<p>\r\nWie kommen Offiziere in d´Höllen,<br>\r\nKapitän und Leutenant?<br>\r\nAuf einem schwarzen Fohlen,<br>\r\nDa wird sie dann der Teufel schon holen.<br>\r\nKapitän, Leutenant…..<br>\r\n</p>\r\n'),
(12, 'Erlkönig', 'Erlkönig, Johann Wolfgang von Goethe (1782)', 'erlkoenig', '<p>\r\nWer reitet so spät durch Nacht und Wind?<br>\r\nEs ist der Vater mit seinem Kind;<br>\r\nEr hat den Knaben wohl in dem Arm,<br>\r\nEr faßt ihn sicher, er hält ihn warm. <br>                       \r\n</p>\r\n<p>\r\n\"Mein Sohn, was birgst du so bang dein Gesicht?\" –<br>\r\n\"Siehst, Vater, du den Erlkönig nicht?<br>\r\nDen Erlenkönig mit Kron\' und Schweif?\" –<br>\r\n\"Mein Sohn, es ist ein Nebelstreif.\"<br>\r\n</p>\r\n<p>\r\n\"Du liebes Kind, komm, geh mit mir!<br>\r\nGar schöne Spiele spiel\' ich mit dir;<br>\r\nManch\' bunte Blumen sind an dem Strand,<br>\r\nMeine Mutter hat manch gülden Gewand.\" –<br>\r\n</p>\r\n<p>\r\n\"Mein Vater, mein Vater, und hörest du nicht,<br>\r\nWas Erlenkönig mir leise verspricht?\" –<br>\r\n\"Sei ruhig, bleibe ruhig, mein Kind;<br>\r\nIn dürren Blättern säuselt der Wind.\" –<br>\r\n</p>\r\n<p>\r\n\"Willst, feiner Knabe, du mit mir gehn?<br>\r\nMeine Töchter sollen dich warten schön;<br>\r\nMeine Töchter führen den nächtlichen Reihn,<br>\r\nUnd wiegen und tanzen und singen dich ein.\" –<br>\r\n</p>\r\n<p>\r\n\"Mein Vater, mein Vater, und siehst du nicht dort<br>\r\nErlkönigs Töchter am düstern Ort?\" –<br>\r\n\"Mein Sohn, mein Sohn, ich seh\' es genau:<br>\r\nEs scheinen die alten Weiden so grau. –\"<br>\r\n</p>\r\n<p>\r\n\"Ich liebe dich, mich reizt deine schöne Gestalt;<br>\r\nUnd bist du nicht willig, so brauch\' ich Gewalt.\" –<br>\r\n\"Mein Vater, mein Vater, jetzt faßt er mich an!<br>\r\nErlkönig hat mir ein Leids getan!\" –<br>\r\n</p>\r\n<p>\r\nDem Vater grauset\'s; er reitet geschwind,<br>\r\nEr hält in Armen das ächzende Kind,<br>\r\nErreicht den Hof mit Mühe und Not;<br>\r\nIn seinen Armen das Kind war tot.<br>\r\n</p>\r\n'),
(13, 'Maria durch ein Dornwald ging', 'Maria durch ein Dornwald ging (~1800)', 'mariadurcheindornwaldging', '<p>\r\nMaria durch ein Dornwald ging,<br>\r\nKyrie eleison.<br>\r\nMaria durch ein Dornwald ging,<br>\r\nder hat in sieben Jahrn kein Laub getragen.<br>\r\nJesus und Maria.<br>\r\n</p>\r\n<p>\r\nWas trug Maria unter ihrem Herzen?<br>\r\nKyrie eleison.<br>\r\nEin kleines Kindlein ohne Schmerzen,<br>\r\ndas trug Maria unter ihrem Herzen.<br>\r\nJesus und Maria.<br>                       \r\n</p>\r\n<p>\r\nDa haben die Dornen Rosen getragen,<br>\r\nKyrie eleison.<br>\r\nAls das Kindlein durch den Wald getragen,<br>\r\nda haben die Dornen Rosen getragen.<br>\r\nJesus und Maria.<br>                      \r\n</p>\r\n'),
(14, 'Ich hatt\' einen Kameraden', 'Ich hatt\' einen Kameraden, Ludwig Uhland (1809)', 'ichhatteinenkameraden', '<p>\r\nIch hatt’ einen Kameraden,<br>\r\nEinen bessern findst du nit.<br>\r\nDie Trommel schlug zum Streite,<br>\r\nEr ging an meiner Seite<br>\r\nIn gleichem Schritt und Tritt.<br>\r\n</p>\r\n<p>\r\nEine Kugel kam geflogen,<br>\r\nGilt’s mir oder gilt es dir?<br>\r\nIhn hat es weggerissen,<br>\r\nEr liegt mir vor den Füßen,<br>\r\nAls wär’s ein Stück von mir.  <br>                         \r\n</p>\r\n<p>\r\nWill mir die Hand noch reichen,<br>\r\nDerweil ich eben lad.<br>\r\nKann dir die Hand nicht geben,<br>\r\nBleib du im ew’gen Leben<br>\r\nMein guter Kamerad!<br>\r\n</p>\r\n'),
(15, 'O du Deutschland ich muss marschieren', 'O du Deutschland ich muss marschieren, Ernst Arndt (1809)', 'odudeutschlandichmussmarschieren', '<p>\r\nO du Deutschland, ich muß marschieren<br>\r\no du Deutschland, du machst mir Mut<br>\r\nMeinen Säbel will ich schwingen<br>\r\nmeine Kugel die soll klingen<br>\r\ngelten soll’s des Feindes Blut<br>\r\n</p>\r\n<p>\r\nNun ade, fahr wohl, Feinsliebchen<br>\r\nWein nicht die Augen rot<br>\r\ntrage dieses Leid geduldig<br>\r\nLeib und Leben bin ich schuldig<br>\r\nes gehört zum Erstern Gott  <br>\r\n</p>\r\n<p>\r\nNun ade, herzliebster Vater<br>\r\nMutter, nimm den Abschiedskuss<br>\r\nFür das Vaterland zu streiten<br>\r\nmahnt es mich nächst Gott zum Zweiten<br>\r\ndass ich von euch scheiden muss<br>\r\n</p>\r\n<p>\r\nAuch ist noch ein Klang erklungen<br>\r\nmächtig mir durch Herz und Sinn<br>\r\nRecht und Freiheit heißt das dritte<br>\r\nund es treibt aus eurer Mitte<br>\r\nmich in Tod und Schlachten hin<br>\r\n</p>\r\n<p>\r\nO wie lieblich die Trommeln schallen<br>\r\nund die Hörner blasen drein<br>\r\nFahnen wehen frisch im Winde<br>\r\nRoss und Männer sind geschwinde<br>\r\nund es muß geschieden sein<br>\r\n</p>\r\n<p>\r\nO du Deutschland ich muß marschieren<br>\r\no du Deutschland, du machst mir Mut<br>\r\nMeinen Säbel will ich schwingen<br>\r\nmeine Kugel, die soll klingen<br>\r\ngelten soll’s des Feindes Blut<br>\r\n</p>\r\n'),
(16, 'O Tannenbaum du trägst ein grünen Zweig', 'O Tannenbaum du trägst ein grünen Zweig (1812)', 'otannenbaumdutraegsteingruenenzweig', '<p>\r\nO Tannebaum, o Tannenbaum<br>\r\ndu trägst ein grünen Zweig<br>\r\nden Winter, den Sommer,<br>\r\ndas dauert die liebe Zeit<br>\r\n</p>\r\n<p>\r\nWenn andere feine Bäumelein<br>\r\nin großer Trauer stehn<br>\r\nso grünst du uns den Winter<br>\r\ndu edler Tannenbaum<br>\r\n</p>\r\n<p>\r\nWarum sollt ich nicht grünen<br>\r\nda ich noch grünen kann<br>\r\nIch hab nicht Vater noch Mutter<br>\r\nder mich versorgen kann<br>\r\n</p>\r\n<p>\r\nUnd der mich kann versorgen<br>\r\ndas ist der liebe Gott<br>\r\nder lässt mich wachsen und grünen<br>\r\ndrum bin ich stark und groß<br>\r\n</p>\r\n'),
(17, 'Freiheit die ich meine', 'Freiheit die ich meine, Max von Schenkendorf (1813)', 'freiheitdieichmeine', '<p>\r\nFreiheit, die ich meine,<br>\r\nDie mein Herz erfüllt,<br>\r\nKomm’ mit deinem Scheine,<br>\r\nSüßes Engelbild.<br>\r\n</p>\r\n<p>\r\nMagst du nie dich zeigen<br>\r\nDer bedrängten Welt?<br>\r\nFührest deinen Reigen<br>\r\nNur am Sternenzelt?<br>\r\n</p>\r\n<p>\r\nAuch bei grünen Bäumen<br>\r\nIn dem lust’gen Wald<br>\r\nUnter Blüthenträumen,<br>\r\nIst dein Aufenthalt.  <br>\r\n</p>\r\n<p>\r\nAch! das ist ein Leben,<br>\r\nWenn es weht und klingt,<br>\r\nWenn dein stilles Weben<br>\r\nWonnig uns durchdringt.<br>\r\n</p>\r\n<p>\r\nWenn die Blätter rauschen<br>\r\nSüßen Freundesgruß,<br>\r\nWenn wir Blicke tauschen,<br>\r\nLiebeswort und Kuß.<br>\r\n</p>\r\n<p>\r\nAber immer weiter<br>\r\nNimmt das Herz den Lauf,<br>\r\nAuf der Himmelsleiter<br>\r\nSteigt die Sehnsucht auf.<br>\r\n</p>\r\n<p>\r\nAus den stillen Kreisen<br>\r\nKommt mein Hirtenkind,<br>\r\nWill der Welt beweisen,<br>\r\nWas es denkt und minnt.<br>\r\n</p>\r\n<p>\r\nBlüht ihm doch ein Garten,<br>\r\nReift ihm doch ein Feld<br>\r\nAuch in jener harten<br>\r\nSteinerbauten Welt.<br>\r\n</p>\r\n<p>\r\nWo sich Gottes Flamme<br>\r\nIn ein Herz gesenkt,<br>\r\nDas am alten Stamme<br>\r\nTreu und liebend hängt;<br>\r\n</p>\r\n<p>\r\nWo sich Männer finden,<br>\r\nDie für Ehr und Recht<br>\r\nMuthig sich verbinden,<br>\r\nWeilt ein frei Geschlecht.<br>\r\n</p>\r\n<p>\r\nHinter dunkeln Wällen<br>\r\nHinter ehrnem Thor<br>\r\nKann das Herz noch schwellen<br>\r\nZu dem Licht empor.<br>\r\n</p>\r\n<p>\r\nFür die Kirchenhallen,<br>\r\nFür der Väter Gruft,<br>\r\nFür die Liebsten fallen,<br>\r\nWenn die Freiheit ruft.<br>\r\n</p>\r\n<p>\r\nDas ist rechtes Glühen<br>\r\nFrisch und rosenroth:<br>\r\nHeldenwangen blühen<br>\r\nSchöner auf im Tod.    <br>                    \r\n</p>\r\n<p>\r\nWollest auf uns lenken<br>\r\nGottes Lieb und Lust.<br>\r\nWollest gern dich senken<br>\r\nIn die deutsche Brust.<br>\r\n</p>\r\n<p>\r\nFreiheit, holdes Wesen,<br>\r\nGläubig, kühn und zart,<br>\r\nHast ja lang erlesen<br>\r\nDir die deutsche Art.<br>\r\n</p>\r\n'),
(18, 'In einem kühlen Grunde', 'In einem kühlen Grunde, Joseph von Eichendorff (1813)', 'ineinemkuehlengrunde', '<p>\r\nIn einem kühlen Grunde<br>\r\nDa geht ein Mühlenrad<br>\r\nMein’ Liebste ist verschwunden,<br>\r\nDie dort gewohnet hat.<br>\r\n</p>\r\n<p>\r\nSie hat mir Treu versprochen,<br>\r\nGab mir ein’n Ring dabei,<br>\r\nSie hat die Treu’ gebrochen,<br>\r\nMein Ringlein sprang entzwei. <br>   \r\n</p>\r\n<p>\r\nIch möcht’ als Spielmann reisen<br>\r\nWeit in die Welt hinaus,<br>\r\nUnd singen meine Weisen,<br>\r\nUnd geh’n von Haus zu Haus.<br>\r\n</p>\r\n<p>\r\nIch möcht’ als Reiter fliegen<br>\r\nWohl in die blut’ge Schlacht,<br>\r\nUm stille Feuer liegen<br>\r\nIm Feld bei dunkler Nacht.<br>\r\n</p>\r\n<p>\r\nHör’ ich das Mühlrad gehen:<br>\r\nIch weiß nicht, was ich will —<br>\r\nIch möcht’ am liebsten sterben,<br>\r\nDa wär’s auf einmal still!<br>\r\n</p>\r\n'),
(19, 'Was ist des Deutschen Vaterland', 'Was ist des Deutschen Vaterland, Ernst Arndt (1813)', 'wasistdesdeutschenvaterland', '<p>\r\nWas ist des Deutschen Vaterland?<br>\r\nIst´s Preussenland, ist´s Schwabenland?<br>\r\nIst´s, wo am Rhein die Rebe blüht?<br>\r\nIst´s, wo am Belt die Möwe zieht?<br>\r\nO nein! nein! nein!<br>\r\nSein Vaterland muss grösser sein!<br>\r\n</p>\r\n<p>\r\nWas ist des Deutschen Vaterland?<br>\r\nIst’s Bayerland, ist’s Steierland?<br>\r\nIst’s, wo des Marsen Rind sich streckt?<br>\r\nIst’s, wo der Märker Eisen reckt?<br>\r\nO nein! nein! nein!<br>\r\nSein Vaterland muss grösser sein!<br>                  \r\n</p>\r\n<p>\r\nWas ist des Deutschen Vaterland?<br>\r\nIst’s Pommerland, Westfalenland?<br>\r\nIst’s, wo der Sand der Dünen weht?<br>\r\nIst’s, wo die Donau brausend geht?<br>\r\nO nein! nein! nein!<br>\r\nSein Vaterland muss grösser sein!<br>                        \r\n</p>\r\n<p>\r\nWas ist des Deutschen Vaterland?<br>\r\nSo nenne mir das grosse Land.<br>\r\nIst’s Land der Schweizer, ist’s Tirol?<br>\r\nDas Land und Volk gefiel mir wohl<br>\r\ndoch nein! nein! nein!<br>\r\nSein Vaterland muss grösser sein!<br>                       \r\n</p>\r\n<p>\r\nWas ist des Deutschen Vaterland?<br>\r\nSo nenne mir das grosse Land.<br>\r\nGewiss, es ist das Österreich<br>\r\nan Ehren und an Siegen reich?<br>\r\nO nein! nein! nein!<br>\r\nSein Vaterland muss grösser sein!<br>                      \r\n</p>\r\n<p>\r\nWas ist des Deutschen Vaterland?<br>\r\nSo nenne endlich mir das Land!<br>\r\nSo weit die deutsche Zunge klingt<br>\r\nund Gott im Himmel Lieder singt,<br>\r\ndas soll es sein!<br>\r\ndas, wackrer Deutscher, nenne dein!<br>\r\ndas nenne dein!<br>                       \r\n</p>\r\n<p>\r\nDas ist des Deutschen Vaterland<br>\r\nwo Eide schwört der Druck der Hand,<br>\r\nwo Treue hell vom Auge blitzt<br>\r\nund Liebe warm im Herzen sitzt.<br>\r\ndas soll es sein!<br>\r\ndas, wackrer Deutscher, nenne dein!<br>\r\ndas nenne dein!<br>                      \r\n</p>\r\n<p>\r\nWas ist des Deutschen Vaterland<br>\r\nwo Zorn vertilgt den welschen Tand<br>\r\nwo jeder Frevler heißet Feind<br>\r\nwo jeder Edle heißet Freund<br>\r\nDas soll es sein, das soll es sein<br>\r\ndas ganze Deutschland soll es sein <br>                       \r\n</p>\r\n<p>\r\nDas ganze Deutschland soll es sein!<br>\r\nO Gott vom Himmel, sieh darein!<br>\r\nUnd gib uns rechten deutschen Mut<br>\r\ndass wir es lieben treu und gut!<br>\r\nDas soll es sein!<br>\r\nDas soll es sein!<br>\r\nDas ganze Deutschland soll es sein!<br>                      \r\n</p>\r\n'),
(20, 'Flamme empor', 'Flamme empor, Johann Nun (1814)', 'flammeempor', '<p>\r\nFlamme empor, Flamme empor.<br>\r\nSteige mit loderndem Scheine<br>\r\nauf die Gebirge vom Rheine<br>\r\nglühend empor, glühend empor.<br>\r\n</p>\r\n<p>\r\nSiehe, wir stehn<br>\r\ntreu im geweiheten Kreise<br>\r\ndich zu des Vaterlands Preise<br>\r\nbrennen zu sehn.<br>\r\n</p>\r\n<p>\r\nHeilige Glut!<br>\r\nRufe die Jugend zusammen,<br>\r\ndass bei den lodernden Flammen<br>\r\nwachse der Mut.<br>\r\n</p>\r\n<p>\r\nHier auf den Höhn<br>\r\nleuchte, du brennendes Zeichen,<br>\r\ndass alle Feinde erbleichen,<br>\r\nwenn sie dich sehn.<br>\r\n</p>\r\n<p>\r\nFinstere Nacht<br>\r\nlag auf Germania\'s Auen:<br>\r\nDa ließ Jehova sich schauen,<br>\r\nder uns bewacht.<br>\r\n</p>\r\n<p>\r\nLicht, brich herein!<br>\r\nSprach er: da sprühten die Flammen,<br>\r\nschlugen in Gluten zusammen<br>\r\nüber dem Rhein.<br>\r\n</p>\r\n<p>\r\nUnd er ist frei!<br>\r\nFlammen umbrausen die Höhen,<br>\r\ndie um den Herrlichen stehen,<br>\r\njauchzt, er ist frei!<br>\r\n</p>\r\n<p>\r\nStehet vereint,<br>\r\nBrüder, und lasst uns mit Blitzen<br>\r\nunsre Gebirge beschützen<br>\r\ngegen den Feinde!<br>\r\n</p>\r\n<p>\r\nLeuchtender Schein!<br>\r\nSiehe, wir singende Paare<br>\r\nschwören am Flammenaltare.<br>\r\nDeutsche zu sein!<br>\r\n</p>\r\n<p>\r\nHöre das Wort!<br>\r\nVater, auf Leben und Sterben,<br>\r\nhilf uns die Freiheit erwerben!<br>\r\nSei unser Hort!<br>\r\n</p>\r\n'),
(21, 'Wenn alle untreu werden', 'Wenn alle untreu werden, Max von Schenkendorf (1814)', 'wennalleuntreuwerden', '<p>\r\nWenn alle untreu werden,<br>\r\nSo bleiben wir doch treu;<br>\r\nDass immer noch auf Erden<br>\r\nFür euch ein Fähnlein sei.<br>\r\nGefährten unsrer Jugend,<br>\r\nihr Bilder bess’rer Zeit,<br>\r\nDie uns zu Männertugend<br>\r\nund Liebestod geweiht.<br>\r\n</p>\r\n<p>\r\nWollt nimmer von uns weichen,<br>\r\nuns immer nahe sein,<br>\r\ntreu wie die deutschen Eichen,<br>\r\nwie Mond und Sonnenschein.<br>\r\nEinst wird es wieder helle,<br>\r\nin aller Brüder Sinn,<br>\r\nsie kehren zu der Quelle<br>\r\nin Lieb und Freude hin.<br>\r\n</p>\r\n<p>\r\nEs haben wohl gerungen<br>\r\ndie Helden dieser Frist,<br>\r\nUnd nun der Sieg gelungen,<br>\r\nübt Satan neue List.<br>\r\nDoch wie sich auch gestalten<br>\r\nim Leben mag die Zeit,<br>\r\nDu sollst uns nicht veralten,<br>\r\no Traum der Herrlichkeit.   <br>      \r\n</p>\r\n<p>\r\nIhr Sterne seid uns Zeugen,<br>\r\ndie ruhig nieder schau’n,<br>\r\nwenn alle Brüder schweigen<br>\r\nund falschen Götzen trau’n.<br>\r\nWir woll’n das Wort nicht brechen<br>\r\nund Buben werden gleich,<br>\r\nwoll’n predigen und sprechen<br>\r\nvom heil’gen Deutschen Reich.    <br>\r\n</p>\r\n');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `song_1600`
--
ALTER TABLE `song_1600`
  ADD PRIMARY KEY (`song_number_1600`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `song_1600`
--
ALTER TABLE `song_1600`
  MODIFY `song_number_1600` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
