-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 25, 2021 at 07:16 PM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 8.0.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `songs`
--

-- --------------------------------------------------------

--
-- Table structure for table `song_1871`
--

CREATE TABLE `song_1871` (
  `song_number_1871` int(4) NOT NULL,
  `title` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `display` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `link` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `content` varchar(4096) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `song_1871`
--

INSERT INTO `song_1871` (`song_number_1871`, `title`, `display`, `link`, `content`) VALUES
(1, 'Heil dir im Siegerkranz', 'Heil dir im Siegerkranz, Heinrich Harries (1871)', 'heildirimsiegerkranz', '<p>\r\nHeil dir im Siegerkranz,<br>\r\nHerrscher des Vaterlands!<br>\r\nHeil, Kaiser, dir!<br>\r\nFühl\' in des Thrones Glanz<br>\r\nDie hohe Wonne ganz,<br>\r\nLiebling des Volks zu sein!<br>\r\nHeil Kaiser, dir!<br>\r\n</p>\r\n<p>\r\nNicht Roß nicht Reisige<br>\r\nSichern die steile Höh\',<br>\r\nWo Fürsten steh\'n:<br>\r\nLiebe des Vaterlands,<br>\r\nLiebe des freien Manns<br>\r\nGründen des Herrschers Thron<br>\r\nWie Fels im Meer.<br>\r\n</p>\r\n<p>\r\nHeilige Flamme, glüh\',<br>\r\nGlüh\' und erlösche nie<br>\r\nFürs Vaterland!<br>\r\nWir alle stehen dann<br>\r\nMutig für einen Mann,<br>\r\nKämpfen und bluten gern<br>\r\nFür Thron und Reich!<br>\r\n</p>\r\n<p>\r\nHandlung und Wissenschaft<br>\r\nHebe mit Mut und Kraft<br>\r\nIhr Haupt empor!<br>\r\nKrieger und Heldenthat<br>\r\nFinde ihr Lorbeerblatt<br>\r\nTreu aufgehoben dort,<br>\r\nAn deinem Thron!<br>\r\n</p>\r\n<p>\r\nSei, Kaiser Wilhelm, hier<br>\r\nLang deines Volkes Zier,<br>\r\nDer Menschheit Stolz!<br>\r\nFühl\' in des Thrones Glanz,<br>\r\nDie hohe Wonne ganz,<br>\r\nLiebling des Volks zu sein!<br>\r\nHeil, Kaiser, dir!<br>\r\n</p>\r\n'),
(2, 'Dunkel war’s der Mond schien helle', 'Dunkel war’s der Mond schien helle (1880)', 'dunkelwarsdermondschienhelle', '<p>\r\nDunkel war’s der Mond schien helle,<br>\r\nSchneebedeckt die grüne Flur<br>\r\nals ein Wagen blitzeschnelle,<br>\r\nlangsam um die Ecke fuhr<br>\r\n</p>\r\n<p>\r\nDrinnen saßen stehend Leute<br>\r\nschweigend ins Gespräch vertieft<br>\r\nals ein totgeschossener Hase<br>\r\nauf der Sandbank Schlittschuh lief<br>\r\n</p>\r\n<p>\r\nUnd der Wagen fuhr im Trabe<br>\r\nrückwärts einen Berg hinauf<br>\r\nDroben zog ein  weißer Rabe<br>\r\ngrade eine Turmuhr auf<br>\r\n</p>\r\n<p>\r\nUnd auf einer roten Bank<br>\r\nDie blau angestrichen war<br>\r\nSaß ein blond gelockter Jüngling<br>\r\nMit kohlrabenschwarzem Haar.<br>\r\n</p>\r\n<p>\r\nRingsumher herrscht tiefes Schweigen<br>\r\nund mit fürchterlichem Krach<br>\r\nspielten in des Grases Zweigen<br>\r\nzwei Kamele lautlos Schach<br>\r\n</p>\r\n<p>\r\nUnd zwei Fische liefen munter<br>\r\ndurch das blaue Kornfeld hin<br>\r\nEndlich ging die Sonne unter<br>\r\nund der graue Tag erschien<br>\r\n</p>\r\n<p>\r\nDroben auf dem Apfelbaume,<br>\r\nder sehr süße Birnen trug,<br>\r\nhing des Frühlings letzte Pflaume<br>\r\nund an Nüssen noch genug.<br>\r\n</p>\r\n'),
(3, 'Frei Weg', 'Frei Weg, Carl Latann (1888)', 'freiweg', '<p>\r\nFrisch in die Welt, wie\'s uns gefällt,<br>\r\nZieh\'n wir mit Sang und Klang hinaus,<br>\r\nWer wandert mit, im gleichen Schritt<br>\r\nUnd lässt wie wir die Sorgen zu Haus?<br>\r\n</p>\r\n<p>\r\nEins, Zwei, Eins, Zwei, munter geht\'s im Takt<br>\r\nUnd jeden hat die Wanderlust gepackt,<br>\r\nLinks, Rechts, Links, Rechts, vorwärts wird gefasst<br>\r\nUnd auf den rechten weg aufgepasst.<br>\r\n</p>\r\n<p>\r\nSchau\'n wir den Lenz so hold er blüht,<br>\r\nWidmen wir ihm das Schönste Lied,<br>\r\nLacht uns der blanke Sonnenschein,<br>\r\nOh welche Lust ein Wandersbursch zu sein.<br>\r\n</p>\r\n<p>\r\nDarum: Frei weg! Darum: Frei weg!<br>\r\nSchöne Welt wir grüßen dich.<br>\r\n</p>\r\n'),
(4, 'Alte Kameraden', 'Alte Kameraden, Carl Teike (1889)', 'altekameraden', '<p>\r\nAlte Kameraden auf dem Marsch durchs Land<br>\r\nSchließen Freundschaft Felsenfest und treu.<br>\r\nOb in Not oder in Gefahr, stets zusammen<br>\r\nHalten sie aufs neu\'.<br>\r\n</p>\r\n<p>\r\nZur Attacke geht es Schlag und Schlag,<br>\r\nRuhm und Ehr\' soll bringen uns der Sieg.<br>\r\nLos, Kameraden, frisch wird geladen,<br>\r\nDas ist unsre Marschmusik.    <br>                    \r\n</p>\r\n<p>\r\nAlter Wein gibt Mut und Kraft;<br>\r\nDenn es schmeckt des Weines Lebenssaft.<br>\r\nSind wir alt, das Herz bleibt jung<br>\r\nUnd gewaltig die Erinnerung.  <br>                      \r\n</p>\r\n<p>\r\nOb in Freude, ob in Not,<br>\r\nBleiben wir getreu bis in den Tod.<br>\r\nTrinket aus und schenket ein<br>\r\nUnd lasst uns alte Kameraden sein.  <br>                      \r\n</p>\r\n<p>\r\nSind wir alt, das Herz bleibt jung,<br>\r\nSchwelgen in Erinnerung.<br>\r\nTrinket aus, schenket ein<br>\r\nUnd lasst uns Kameraden sein.  <br>                     \r\n</p>\r\n'),
(5, 'Bei Müllers hats gebrannt', 'Bei Müllers hats gebrannt (~1900)', 'beimuellershatgebrannt', '<p>\r\nBei Müllers hats gebrannt, brannt, brannt.<br>\r\nDa bin ich hingerannt, rannt, rannt.<br>\r\nDa stand ein Polizist, zist, zist,<br>\r\nDer schrieb mich auf die List, List, List.<br>\r\n</p>\r\n<p>\r\nDie List, die fiel in´n Dreck, Dreck, Dreck.<br>\r\nDa war mein Name weg, weg, weg.<br>\r\nDa lief ich schnell nach Haus, Haus, Haus<br>\r\nZu meinem Onkel Klaus, Klaus, Klaus.<br>\r\n</p>\r\n<p>\r\nDer Klaus der lag im Bett, Bett, Bett<br>\r\nbei seiner Frau Elisabeth.<br>\r\nElisabeth, die lachte<br>\r\nDer Büstenhalter krachte<br>\r\n</p>\r\n<p>\r\nDer Bauch der explodierte<br>\r\nEin Baby rauschmarschierte<br>\r\nGleich in den ersten Stock<br>\r\nDa stand ein Mann im Unterrock<br>\r\n</p>\r\n<p>\r\nBei Müllers  hatt’s gebrannt,<br>\r\nDa bin ich hingerannt.<br>\r\nDo war a kleener Zaun,<br>\r\nDo wollt ich Äppel klaun<br>\r\nDo kam der Herr Schandarm<br>\r\nUnd nahm mich untern Arm,<br>\r\nDer führt mich um die Eck<br>\r\nUnd plötzlich war ich weg<br>\r\n</p>\r\n'),
(6, 'Droben im Oberland', 'Droben im Oberland (1900)', 'drobenimoberland', '<p>\r\nDroben im Oberland<br>\r\nei da ist es wunderfein<br>\r\nDa ist die Jägerei<br>\r\nda ist das Schießen frei<br>\r\nda möcht ich Oberjäger sein,<br>\r\nschießen, das ist meine Freud<br>\r\n</p>\r\n<p>\r\nSchiaß mir an Gamsbock z´samm<br>\r\nFallt er oder fallt er net?<br>\r\nFallt er net, so bleibt er stehn,<br>\r\nZu meinem Madel muaß i gehn,<br>\r\nZu meinem Madel muß i gehn,<br>\r\nAlle Woch sechs- siebenmal.<br>\r\n</p>\r\n<p>\r\nGestern ist Sonntag gwe,<br>\r\nEi, da war sie wieder da.<br>\r\nSie hat ein Hütlein auf<br>\r\nMit einer wunderschönen Feder drauf<br>\r\nSie sah so reizend, reizend aus<br>\r\nUnd sie ging mit mir nach Haus.<br>\r\n</p>\r\n<p>\r\nKommt eine schöne Jungfrau daher<br>\r\nei die ist so wundernett<br>\r\nSie hat ein Hütlein auf, eine schöne weiße Feder drauf<br>\r\nsie sah so reizend, reizend aus<br>\r\nund ich ging mit ihr nach Haus<br>\r\n</p>\r\n<p>\r\nAn ihrer Haustür angekommen<br>\r\nei da sagte sie zu mir<br>\r\nDu hast mich heimgebracht<br>\r\nnun gib mir unverzagt<br>\r\nauf meinen rosenroten Mund<br>\r\neinen zuckersüßen Kuss<br>\r\n</p>\r\n<p>\r\nLauter junge, hübsche Leut sein´s mir<br>\r\nlauter hübsche, junge Leut!<br>\r\nWenn die hübschen, jungen Leut net wärn<br>\r\nwer sollt das viele Geld verzehrn?<br>\r\nLauter junge, hübsche Leut sein´s mir<br>\r\nlauter hübsche, junge Leut!<br>\r\n</p>\r\n'),
(7, 'Bub und Spinne gingen in den Wald', 'Bub und Spinne gingen in den Wald (1908)', 'bubundspinnegingenindenwald', '<p>\r\nBub und Spinne, Bub und Spinne<br>\r\ngingen in den Wald<br>\r\nda warn dem Bub da warn dem Bub<br>\r\ndie Beine kalt<br>\r\n</p>\r\n<p>\r\nDi holla di, Di Holla ho di ho<br>\r\ndi holla holla di, holla holla ho<br>\r\ndi hola di di holla ho<br>\r\ndi holla holla hi ha ho<br>\r\n</p>\r\n<p>\r\nDa macht die Spinne<br>\r\nein Feuer an<br>\r\ndamit der Bub<br>\r\nsich wärmen kann<br>\r\n</p>\r\n<p>\r\nDa kam ein Böser<br>\r\nWirbelwind<br>\r\nder macht das Feuer<br>\r\naus geschwind<br>\r\n</p>\r\n<p>\r\nDa wurd die Spinne<br>\r\närgerlich<br>\r\nund spuckt dem Bub<br>\r\nins Angesicht<br>\r\n</p>\r\n<p>\r\nDa kam ein guter<br>\r\nWandersmann<br>\r\nder macht das Feuer<br>\r\nwieder an<br>\r\n</p>\r\n<p>\r\nDa wurd die Spinne<br>\r\nwieder gut<br>\r\nda kann man sehn<br>\r\nwas Liebe tut<br>\r\n</p>\r\n'),
(8, 'Ein schöner Tag zu Ende geht', 'Ein schöner Tag zu Ende geht (1910)', 'einschoenertagzuendegeht', '<p>\r\nEin schöner Tag zu Ende geht<br>\r\ndie Sterne sind erwacht<br>\r\nwir reichen uns die Hände nun<br>\r\nund sagen „Gute Nacht“<br>\r\nVon Ort zu Ort, von Land zu Land<br>\r\nerklingt ein Lied darein<br>\r\nreicht eure Hände fest zum Bund<br>\r\nWir wollen Freunde sein<br>\r\n</p>\r\n<p>\r\nEin neuer Tag bricht bald herein<br>\r\nder weit uns sehen soll<br>\r\nzum Abschied reicht euch nun die Hand<br>\r\nund saget „Lebewohl“<br>\r\nVon Ort zu Ort, von Land zu Land<br>\r\nerklingt ein Lied darein<br>\r\nreicht eure Hände fest zum Bund<br>\r\nWir wollen Freunde sein<br>\r\n</p>\r\n<p>\r\nOb Nord, ob Süd, ob Ost, ob West<br>\r\nwo du auch stehst, ist gleich<br>\r\nein Freundeskreis durchzieht die Welt<br>\r\nHorch auf, die Zeit ist reif<br>\r\nVon Ort zu Ort, von Land zu Land<br>\r\nerklingt ein Lied darein<br>\r\nreicht eure Hände fest zum Bund<br>\r\nWir wollen Freunde sein<br>\r\n</p>\r\n'),
(9, 'Wenn der Hund mit der Wurst über´n Spucknapf springt', 'Wenn der Hund mit der Wurst über´n Spucknapf springt (1911)', 'wennderhundmitderwurst', '<p>\r\nWenn der Hund mit der Wurst über´n Spucknapf springt<br>\r\nund der Storch in der Luft den Frosch verschlingt<br>\r\n</p>\r\n<p>\r\nWenn der Storch in der Luft über´n Spucknapf springt<br>\r\nund der Hund mit der Wurst den Frosch verschlingt<br>\r\n</p>\r\n<p>\r\nWenn der Frosch mit dem Storch über´n Spucknapf springt<br>\r\nund der Hund in der Luft die Wurst verschlingt<br>\r\n</p>\r\n<p>\r\nWenn die Wurst mit dem Hund über´n Spucknapf springt<br>\r\nund der Frosch in der Luft den Storch verschlingt<br>\r\n</p>\r\n<p>\r\nWenn der Spucknapf mit der Wurst über´n Frosch wegspringt<br>\r\nund die Luft mit dem Hund den Storch verschlingt<br>\r\n</p>\r\n<p>\r\nWenn die Luft mit dem Storch über die Wurst wegspringt<br>\r\nund der Spucknapf mit dem Frosch den Hund verschlingt<br>\r\n</p>\r\n<p>\r\nWenn die Wurst mit dem Spucknapf über´n Storch wegspringt<br>\r\nund der Frosch mit dem Hund die Luft verschlingt<br>\r\n</p>\r\n<p>\r\nWenn der Storch mit dem Spucknapf über die Luft wegspringt<br>\r\nund die Wurst mit dem Frosch den Hund verschlingt<br>\r\n</p>\r\n'),
(10, 'Hab Sonne im Herzen ob´s stürmt', 'Hab Sonne im Herzen ob´s stürmt, Michael Englert (1913)', 'habsonneimherzenobsstuermt', '<p>\r\nHab Sonne im Herzen, ob´s stürmt oder schneit.<br>\r\nob Himmel voll Wolken, die Erde voll Streit!<br>\r\nHab Sonne im Herzen, dann komme, was mag!<br>\r\nDas leuchtet voll Licht dir den dunkelsten Tag!<br>\r\n</p>\r\n<p>\r\nHab ein Lied auf den Lippen mit fröhlichem Klang,<br>\r\nund macht auch des Alltags Gedränge dich bang!<br>\r\nHab ein Lied auf den Lippen, dann komme, was mag!<br>\r\nDas hilft dir verwinden den einsamsten Tag!<br>\r\n</p>\r\n<p>\r\nHab ein Wort auch für andre in Sorg‘ und in Pein<br>\r\nund sag, was dich selber so frohgemut läßt sein:<br>\r\nHab ein Lied auf den Lippen, verlier nie den Mut,<br>\r\nhab Sonne im Herzen und alles wird gut!<br>\r\n</p>\r\n'),
(11, 'Argonnerwald um Mitternacht', 'Argonnerwald um Mitternacht (~1914)', 'argonnerwaldummitternacht', '<p>\r\nArgonnerwald, um Mitternacht<br>\r\nEin Pionier stand auf der Wacht<br>\r\nEin Sternlein hoch am Himmel stand<br>\r\nBringt ihm ´nen Gruß aus fernem Heimatland<br>\r\n</p>\r\n<p>\r\nUnd mit dem Spaten in der Hand<br>\r\nEr vorne in der Sappe stand.<br>\r\nMit Sehnsucht denkt er an sein Lieb:<br>\r\nOb er sie wohl noch einmal wiedersieht?<br>\r\n</p>\r\n<p>\r\nUnd donnernd dröhnt die Artill’rie.<br>\r\nWir stehen vor der Infantrie.<br>\r\nGranaten schlagen bei uns ein,<br>\r\nDer Franzmann will in unsere Stellung ‚rein.<br>\r\n</p>\r\n<p>\r\nEr frug nicht warum und nicht wie,<br>\r\nTat seine Pflicht wie alle sie.<br>\r\nIn keinem Liede ward´s gehört,<br>\r\nOb er geblieben oder heimgekehrt.<br>\r\n</p>\r\n<p>\r\nBedroht der Feind uns noch so sehr,<br>\r\nWir Deutsche fürchten ihn nicht mehr.<br>\r\nUnd ob er auch so stark mag sein,<br>\r\nIn unsere Stellung kommt er doch nicht ‚rein.<br>\r\n</p>\r\n<p>\r\nDer Sturm bricht los, die Mine kracht,<br>\r\nDer Pionier gleich vorwärts macht.<br>\r\nBis an den Feind macht er sich ran<br>\r\nUnd zündet dann die Handgranate an.<br>\r\n</p>\r\n<p>\r\nDie Infantrie steht auf der Wacht,<br>\r\nBis daß die Handgranate kracht,<br>\r\nGeht dann mit Sturm bis an den Feind,<br>\r\nMit Hurra nimmt sie dann die Stellung ein.<br>\r\n</p>\r\n<p>\r\nDer Franzmann ruft: Pardon Monsieur!<br>\r\nHebt beide Hände in die Höh,<br>\r\nEr fleht uns dann um Gnade an,<br>\r\nDie wir als Deutsche ihm gewähren dann.<br>\r\n</p>\r\n<p>\r\nBei diesem Sturm viel Blut auch floß,<br>\r\nManch junges Leben hat’s gekost´.<br>\r\nWir Deutsche aber halten stand,<br>\r\nFür das geliebte, teure Vaterland.<br>\r\n</p>\r\n<p>\r\nArgonnerwald, Argonnerwald,<br>\r\nEin stiller Friedhof wirst du bald!<br>\r\nIn deiner kühlen Erde ruht<br>\r\nSo manches tapfere Soldatenblut.<br>\r\n</p>\r\n<p>\r\nUnd komm‘ ich einst zur Himmelstür,<br>\r\nEin Engel Gottes steht dafür:<br>\r\nArgonnerkämpfer, tritt herein,<br>\r\nHier soll für dich der ew’ge Friede sein.<br>\r\n</p>\r\n<p>\r\nDu Pionier um Mitternacht,<br>\r\nHeut‘ steht ganz Deutschland auf der Wacht.<br>\r\nIn Treue fest, im Wollen rein,<br>\r\nAls eine neue starke Wacht am Rhein !<br>\r\n</p>\r\n'),
(12, 'Die blauen Dragoner', 'Die blauen Dragoner, G.W. Harmssen (1914)', 'dieblauendragoner', '<p>\r\nDie blauen Dragoner, sie reiten<br>\r\nMit klingendem Spiel durch das Tor,<br>\r\nFanfaren sie begleiten<br>\r\nHell zu den Hügeln empor.<br>                       \r\n</p>\r\n<p>\r\nDie wiehernden Rosse, sie stampfen,<br>\r\nDie Birken, die wiegen sich lind,<br>\r\nDie Fähnlein auf den Lanzen<br>\r\nFlattern im Morgenwind.<br>                        \r\n</p>\r\n<p>\r\nMorgen, da müssen sie reiten,<br>\r\nMein Liebster wird bei ihnen sein.<br>\r\nMorgen in alle Weiten<br>\r\nMorgen, da bin ich allein.<br>                        \r\n</p>\r\n<p>\r\nDie blauen Dragoner, sie reiten<br>\r\nMit klingendem Spiel durch das Tor,<br>\r\nFanfaren sie begleiten<br>\r\nHell zu den Hügeln empor.<br>                     \r\n</p>\r\n'),
(13, 'Eine Muh eine Mäh', 'Eine Muh eine Mäh, Wilhelm Lindemann (1914)', 'einemuheinemaeh', '<p>\r\nEine Muh, eine Mäh,<br>\r\neine Täterätätä,<br>\r\neine Tute, eine Rute,<br>\r\neine Hopp-hopp-hopp-hopp,<br>\r\neine Diedeldadeldum,<br>\r\neine Wau-wau-wau,<br>\r\nratatsching-daderatabum.<br>\r\n</p>\r\n<p>\r\nWenn der Weihnachtsbaum uns lacht,<br>\r\nwenn die Glocke bim-bam macht,<br>\r\nkommt auf leisen Sohlen,<br>\r\nRuprecht an verstohlen.<br>\r\nZieht mit vollen Säcken ein,<br>\r\nbringt uns Bäcker-Leckerein<br>\r\nund packt unter Lachen<br>\r\naus die schönsten Sachen.<br>\r\nKommt, Kinder, seht euch satt,<br>\r\nwas er für Schätze hat:<br>\r\nEine Muh, eine Mäh,<br>\r\neine Täterätätä,<br>\r\neine Tute, eine Rute,<br>\r\neine Hopp-hopp-hopp-hopp,<br>\r\neine Diedeldadeldum,<br>\r\neine Wau-wau-wau,<br>\r\nratatsching-daderatabum.<br>                        \r\n</p>\r\n<p>\r\nWenn der Schnee zum Berg sich türmt,<br>\r\nwenn es draußen friert und stürmt,<br>\r\num die Weihnachtslichter<br>\r\nfröhliche Gesichter.<br>\r\nAlle Stuben blitzeblank,<br>\r\ndenn es kommt mit Poltergang<br>\r\ndurch die Luft, die kalte,<br>\r\nRuprecht an, der alte.<br>\r\nUnd pustet, prustet – dann<br>\r\nzeigt uns der Weihnachtsmann:<br>\r\nEine Muh, eine Mäh,<br>\r\neine Täterätätä,<br>\r\neine Tute, eine Rute,<br>\r\neine Hopp-hopp-hopp-hopp,<br>\r\neine Diedeldadeldum,<br>\r\neine Wau-wau-wau,<br>\r\nratatsching-daderatabum.<br>                     \r\n</p>\r\n<p>\r\nDer Weihnachtsmann ist da,<br>\r\nDer Weihnachtsmann ist da,<br>\r\nDer Weihnachtsmann ist da!<br>                     \r\n</p>\r\n'),
(14, 'Reservisten sind wir nun', 'Reservisten sind wir nun (1914)', 'reservistensindwirnun', '<p>\r\nReservisten sind wir nun<br>\r\ntragen munter Stöcke<br>\r\nsind gelenkig, nicht mehr steif<br>\r\nwie Rekrutenböcke<br>\r\nziehen fröhlich in die Welt<br>\r\nund verdienen fleißig Geld<br>\r\ndaß es gut uns gehe<br>\r\n</p>\r\n<p>\r\nWerden stets gedenken gern<br>\r\nan die Dienstzeit in dem Heere<br>\r\nwo so vieles wir gelernt<br>\r\nZucht und Mannes Ehre<br>\r\nWo gestählt wir Kraft und Mut<br>\r\nHeißa frisch Soldatenblut<br>\r\nrollt in unsern Adern<br>\r\n</p>\r\n<p>\r\nUnd so bleibt es fernerhin<br>\r\nwas uns auch begegne<br>\r\nuns beseelt der eine Wunsch<br>\r\n„Lieber Herrgott, segne<br>\r\nunser deutsches Vaterland<br>\r\nhalte schützend deine Hand<br>\r\nüber alles Deutsche!“<br>\r\n</p>\r\n<p>\r\nDeutsch bleibt unser Herz und Sinn<br>\r\nund mit kräft´gen Hieben<br>\r\nwürdig einer deutschen Faust<br>\r\nwird der Feind vetrieben<br>\r\nBleibt ein jeder Reservist<br>\r\ndeutsch, dabei ein guter Christ<br>\r\ndann muß Deutschland blühen<br>\r\n</p>\r\n'),
(15, 'Gäb es nur eine Krone', 'Gäb es nur eine Krone (1915)', 'gaebesnureinekrone', '<p>\r\nGäb es nur eine Krone<br>\r\nwohlan, ich schenkte sie,<br>\r\nder Tapferkeit zum Lohne,<br>\r\nder deutschen Infanterie.<br>\r\n</p>\r\n<p>\r\nSie hat den Ruhm, der nie vergeht,<br>\r\nder ewig in den Sternen steht,<br>\r\nsich vor der ganzen Welt erworben.<br>\r\nMit Waffen leicht, mit Waffen schwer,<br>\r\nKompanie an Kompanie,<br>\r\nist sie die Königin im Heer,<br>\r\ndie deutsche Infanterie<br>\r\n</p>\r\n<p>\r\nInfanterie, du trägst die Krone aller Waffen,<br>\r\nInfanterie, du trägst mit Stolz den schweren Affen,<br>\r\nInfanterie, ja dich vergess ich nie.<br>\r\nDu trägst mit Stolz den Ruhm aus längst vergangner Zeit<br>\r\nhinein in alle Ewigkeit.<br>\r\n</p>\r\n<p>\r\nGäb es für Sieg und Sterben<br>\r\nnur eine Melodie,<br>\r\nsie müßt gesungen werden,<br>\r\nder deutschen Infanterie.<br>\r\n</p>\r\n<p>\r\nEin Lied, das aus den Gräben dringt,<br>\r\nein Lied, das durch die Zeiten klingt,<br>\r\nvon Helden die da starben.<br>\r\nMit Waffen leicht, mit Waffen schwer,<br>\r\nKompanie an Kompanie,<br>\r\nist sie die Königin im Heer,<br>\r\ndie deutsche Infanterie.<br>\r\n</p>\r\n<p>\r\nInfanterie, du trägst die Krone aller Waffen,<br>\r\nInfanterie, du trägst mit Stolz den schweren Affen,<br>\r\nInfanterie, ja dich vergess ich nie.<br>\r\nDu trägst mit Stolz<br>\r\nden Ruhm aus längst vergangner Zeit<br>\r\nhinein in alle Ewigkeit.<br>\r\n</p>\r\n<p>\r\nAuch unsre Väter standen,<br>\r\nin einer Kompanie,<br>\r\nund wenn ein Lied sie sangen,<br>\r\ngalt es der Infanterie.<br>\r\nSie hat den Ruhm, der nie vergeht<br>\r\nder ewig in den Sterne steht<br>\r\nbraucht sich nicht vor der Welt zu schämen<br>\r\nMit Waffen leicht, mit Waffen schwer,<br>\r\nKompanie an Kompanie,<br>\r\nist sie die Königin im Heer,<br>\r\ndie deutsche Infanterie<br>\r\n</p>\r\n'),
(16, 'Im grünen Wald da wo die Drossel singt', 'Im grünen Wald da wo die Drossel singt, Friederike Kempner (1915)', 'imgruenenwalddawodiedrosselsingt', '<p>\r\nIm grünen Wald<br>\r\nDort wo die Drossel singt,<br>\r\nUnd im Gebüsch<br>\r\nDas muntre Rehlein springt,<br>\r\nWo Tann\' und Fichten<br>\r\nStehn am Waldessaum,<br>\r\nVerlebt ich meiner Jugend<br>\r\nSchönsten Traum.<br>\r\n</p>\r\n<p>\r\nDas Rehlein trank<br>\r\nAus einem klaren Bach,<br>\r\nDieweil im Wald<br>\r\nDer Kuckuck lustig lacht,<br>\r\nDer Jäger zielt schon<br>\r\nHinter einem Baum,<br>\r\nDa war vorbei des Rehleins<br>\r\nLebenstraum. <br>\r\n</p>\r\n<p>\r\nGetroffen wars<br>\r\nUnd sterbend lag es da,<br>\r\nDas man vorher<br>\r\nNoch munter hüpfen sah,<br>\r\nDa trat der Jäger<br>\r\nAus des Waldes Saum<br>\r\nUnd sprach: Das Leben ist ja<br>\r\nNur ein Traum!<br>\r\n</p>\r\n'),
(17, 'Wildgänse rauschen durch die Nacht', 'Wildgänse rauschen durch die Nacht, Walter Flex (1915)', 'wildgaenserauschendurchdienacht', '<p>\r\nWildgänse rauschen durch die Nacht<br>\r\nmit schrillem Schrei nach Norden;<br>\r\nUnstete Fahrt habt Acht, habt Acht,<br>\r\ndie Welt ist voller Morden.<br>\r\n</p>\r\n<p>\r\nFahrt durch die nachtdurchwogte Welt,<br>\r\ngraureisige Geschwader!<br>\r\nFahlhelle zuckt und Schlachtruf gellt,<br>\r\nweit wallt und wogt der Hader.<br>\r\n</p>\r\n<p>\r\nRausch zu, fahr zu, du graues Heer!<br>\r\nRauscht zu, fahrt zu nach Norden!<br>\r\nFahrt ihr nach Süden übers Meer,<br>\r\nwas ist aus uns geworden?<br>\r\n</p>\r\n<p>\r\nWir sind wie ihr ein graues Heer<br>\r\nund fahr’n in Kaisers Namen<br>\r\nUnd fahr’n wir ohne Wiederkehr,<br>\r\nrauscht uns im Herbst ein Amen<br>\r\n</p>\r\n'),
(18, 'Wo alle Straßen enden', 'Wo alle Straßen enden (~1915)', 'woallestrassenenden', '<p>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>\r\n</p>\r\n<p>\r\nWo alle Straßen enden,<br>\r\nhört unser Weg nicht auf.<br>\r\nWohin wir uns auch wenden,<br>\r\ndie Zeit nimmt ihren Lauf.<br>\r\nDas Herz verbrannt,<br>\r\nim Schmerz verbannt.<br>\r\nSo ziehen wir verloren<br>\r\ndurch das graue Niemandsland.<br>\r\nVielleicht kehrt von uns<br>\r\nkeiner mehr zurück ins Heimatland.<br>                   \r\n</p>\r\n<p>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>\r\nWir sind verloren.<br>                   \r\n</p>\r\n'),
(19, 'Hinaus in die Ferne mit Butterbrot und Speck', 'Hinaus in die Ferne mit Butterbrot und Speck (1916)', 'hinausindiefernemitbutterbrotundspeck', '<p>\r\nHinaus in die Ferne mit<br>\r\nButterbrot und Speck<br>\r\nDas mag ich ja so gerne<br>\r\ndas nimmt mir keiner weg.<br>\r\nUnd wer das tut,<br>\r\ndem hau ich auf die Nase,<br>\r\nDem hau ich auf die Schnut´<br>\r\ndaß es blut´<br>\r\n</p>\r\n'),
(20, 'Weit ist der Weg zurück ins Heimatland', 'Weit ist der Weg zurück ins Heimatland (1917)', 'weitistderwegzurueckinsheimatland', '<p>\r\nWeit ist der Weg zurück ins Heimatland,<br>\r\nja weit, so weit.<br>\r\nDort bei den Sternen überm Waldesrand<br>\r\nLacht die alte Zeit.<br>\r\nJeder brave Musketier<br>\r\nSehnt heimlich sich nach dir.<br>\r\nJa, weit ist der Weg zurück ins Heimatland,<br>\r\nJa weit, so weit.<br>\r\n</p>\r\n<p>\r\nHoch weht die Fahne in dem Morgenwind,<br>\r\nSo hoch, so Hoch.<br>\r\nViele, die ihr so treu gefolget sind,<br>\r\nHolt der Schnitter Tod.<br>\r\nUnd die alte schöne Zeit,<br>\r\nSie kommt ja nimmermehr.<br>\r\nJa! Hoch weht die Fahne nun trotz aller Not.<br>\r\nWir folgen ihr.<br>\r\n</p>\r\n<p>\r\nDrum haltet aus und kommt es schlimmer noch,<br>\r\ndrauf und dran!<br>\r\nWer soll denn leben unter diesem Joch?<br>\r\nStürmt den Berg hinan!<br>\r\nFällt es uns auch noch so schwer,<br>\r\nWir weichen nimmermehr.<br>\r\nJa, heut muß der Sieg wie immer unser sein,<br>\r\nWir glauben dran.<br>\r\n</p>\r\n'),
(21, 'Ich bin ein Deutscher kennt ihr meine Farben', 'Ich bin ein Deutscher kennt ihr meine Farben', 'ichbineindeutscherkenntihrmeinefarben', '<p>\r\nIch bin ein Deutscher kennt ihr meine Farben?<br>\r\nDie Fahne schwebt mir schwarz-weiß-rot voran<br>\r\nDass für die Freiheit meine Väter starben<br>\r\nDas deuten, merkt es, meine Farben an.<br>\r\nNie werd´ ich bang verzagen<br>\r\nWie jene will ich´s wagen<br>\r\nSei´s trüber Tag, sei´s heitrer Sonnenschein<br>\r\nich bin ein Deutscher, will ein Deutscher sein!<br>\r\n</p>\r\n');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `song_1871`
--
ALTER TABLE `song_1871`
  ADD PRIMARY KEY (`song_number_1871`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `song_1871`
--
ALTER TABLE `song_1871`
  MODIFY `song_number_1871` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
